### ISSUE TITLE
Can this program work with SDK 2.1 ?

### ISSUE THREAD

**Issue by timmycheng522** [ibaiGorordo/IWR1443-Read-Data-Python#1]
I'm using a AWR1443, that flashs a SDK 2.1 demo binary file. Because it's failed to flash the 1.2 demo bin file. What if I wanna run the program to read my device's data, you have any advice for it ? Where should I modify your program?
I already tried to modify 1443 configure file, that changed sdk ver 01.02 to sdk ver 02.01, but it didn't work.

**Comment by ibaiGorordo** [comment]
I am sorry for the late response, I did not get any notification.

I am not sure about the SDK 2.1 because my board is old and only works with the version 1.02. 

My guess is that it might work with the SDK 2.1 the AWR1642 repository. You could try to add these code in the 185 line (in readData_IWR1443.py) after reading the number of TLV.
```
subFrameNumber = np.matmul(byteBuffer[idX:idX+4],word)
idX += 4
```

Since your question was long time ago I guess you already fixed it. Could you write how you did it? In case there is other people with the same problem.

Thank you

**Comment by agangavaram** [comment]
Hi,
This python code does work well with sdk kit 2.1. Just copy the sdk 2.1 demo config file and use that instead of the provided config file. We implemented this code to classify gestures and it was able to read from the data port and return the data we needed, so this code does work well. The only change needed is the config file.

**Comment by ibaiGorordo** [comment]
Hi,

Thank you for your message. I am glad to hear that you could use it for your project. 

Therefore, I will close this issue.
