### ISSUE TITLE
Is this code compatible with IWR1443 ES3.0, SDK2.1?

### ISSUE THREAD

**Issue by KamiCalcium** [ibaiGorordo/IWR1443-Read-Data-Python#10]
Hi,

Thank you very much for the code.

I'm using IWR1443 ES3.0 with SDK2.1 and trying to get 3D point cloud data. I searched for so many forums and used different github repository but nothing works. It looks like ES2.0 is very different from ES3.0. Most of the repository either only support ES1 or ES2. The only thing work is the mmWave studio 2.1, sadly there isn't 2D plot nor 3D plot.

I'm just wondering is this code compatible with ES3.0 SDK2.1?

**Comment by ibaiGorordo** [comment]
Hi, 

When I made this code, the IWR1443 only run in the SDK 1.02, so this repository is focused on that version. I have not checked with the new ES versions, but rather than the ES version, the important thing for compatibility is the SDK version.

As you mention, if you have the SDK 2.1, then you should use this other repository (ignore the fact it says AWR1642):
https://github.com/ibaiGorordo/AWR1642-Read-Data-Python-MMWAVE-SDK-2

If you upgrade the SDK in your radar to the new 3.5, then you should use this repository instead:
https://github.com/ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-

Also, have you tested the mmWave demo visualizer? In you case with the SDK version 2.1 you should use this link:
https://dev.ti.com/gallery/view/mmwave/mmWave_Demo_Visualizer/ver/2.1.0/

Regards,
Ibai

**Comment by gongpx20069** [comment]
Hi, 
Thanks for your code. My IWR1443 verson is ES3.0, and its SDK is 2.1. When I use this repository, it works normally, but the point cloud collected has a delay of about seven seconds. When I use the repository https://github.com/ibaiGorordo/AWR1642-Read-Data-Python-MMWAVE-SDK-2, my radar cannot work normally. 
So what should I do. Thanks for your nice code again.

**Comment by ibaiGorordo** [comment]
Did you modify the config file when you used the other repository? That config file is for the AWR1642, so it will probably not work properly with your board, if you have not done it yet, use the demo visualizer as I mentioned to get the new config file.

Also, if you uncomment lines 188-189 in this repository, it will probably work as expected. https://github.com/ibaiGorordo/IWR1443-Read-Data-Python-MMWAVE-SDK-1/blob/5a95f5e72292fa1148d6096e39547fe96b4c8c14/readData_IWR1443.py#L188-L189

**Comment by gongpx20069** [comment]
> Did you modify the config file when you used the other repository? That config file is for the AWR1642, so it will probably not work properly with your board, if you have not done it yet, use the demo visualizer as I mentioned to get the new config file.
> 
> Also, if you uncomment lines 188-189 in this repository, it will probably work as expected.
> 
> https://github.com/ibaiGorordo/IWR1443-Read-Data-Python-MMWAVE-SDK-1/blob/5a95f5e72292fa1148d6096e39547fe96b4c8c14/readData_IWR1443.py#L188-L189

When I uncomment lines 188-189 in this repository, and use the config file from demo visualizer, the radar cannot collect any point.  At present, It seems that only the code in this repository can adapt to SDK 2.1. Although there is a delay of more than 7 seconds.

**Comment by ibaiGorordo** [comment]
You will have to do some debugging of the data (print version, numTLVs, tlv_type) you are getting because it the behavior you are mentioning is not normal.
- This repository should not work well with the SDK 2.1 because the data from the radar has a slightly different format between SDK versions 1 and 2 (which is the additional subFrameNumber I mentioned you to uncomment). When you say it has 7 second delay, does the data make sense? Because if the data is nor being parse properly it is probably going to be plotting bad data.
- What demo visualizer did you use to create the config file? Can you share the config file you created? Does that config file work well in the demo visualizer?
- I think your board should be supported in the SDK version 3, so try upgrading the firmware.

**Comment by gongpx20069** [comment]
- the demo visualizer I used is https://dev.ti.com/gallery/view/mmwave/mmWave_Demo_Visualizer/ver/2.1.0/. I downloaded the config file from the button of "SAVE CONFIG TO PC". When I load config file in this repository to demo visualizer, it can work with no delay. 
- My iwr1443 is verson ES3.0. But when I upgrad the firmware, the iwr1443 cannot work. 
- It seems that the data collected by the code is sense. Because I move back and forth in front of the radar, the point cloud in the X-Y coordinate system also moves back and forth.
-  Where can I download iwr1443 different versions of data format analysis?
Thank you very much!

**Comment by gongpx20069** [comment]
Thanks for your reply. I find the data structure from the "mmw Demo Data Structure_8_16.pdf", and I try to understand your code. I cannot understand why should we use "numTLVs" loop in line 192. In the loop, the 'detObj' is rewrited in every cycle.

**Comment by gongpx20069** [comment]
I solved this problem. I print the 'numTLVs=1', and the 'detObj' is the number of points. SDK2.1's data format is as same as SDK1.x.  
The delay is due to the processing speed of the computer. In every cycle, we use time.sleep() function, which makes the byteBufferLength too long to process in time. If we start a new thread and remove the time.sleep() function, the delay will go down, and the byteBufferLength will be short. 

Thanks for your code. It is useful.

**Comment by ibaiGorordo** [comment]
Glad to hear that. True, I have just checked the source code of the demo visualizer and the part I mentioned to uncomment is only for the 16XX and 18XX boards:

```
    // subFrame number, uint32
    if (((Params.platform == mmwInput.Platform.xWR16xx)||(Params.platform == mmwInput.Platform.xWR18xx)) && (Params.tlv_version_uint16 >= 0x0101)) {
        Params.currentSubFrameNumber = math.sum(math.dotMultiply(bytevec.slice(byteVecIdx, byteVecIdx + 4), byte_mult));
        byteVecIdx += 4;
        if (Params.dfeDataOutputMode.mode != 3) {
            /*make sure this is set to zero when legacy frame is used*/
            Params.currentSubFrameNumber = 0;
        }
    } 
    else {
        Params.currentSubFrameNumber = 0;
    }
```
