### ISSUE TITLE
how to locate serial port

### ISSUE THREAD

**Issue by yujianyuanhaha** [ibaiGorordo/IWR1443-Read-Data-Python#13]
greetings,

and wonderful job!

how can we locate the serial port like
```
# Windows
    CLIport = serial.Serial('COM3', 115200)
    Dataport = serial.Serial('COM4', 921600)
```

I follow 1443 manual and the mmW Studio just save down the `.bin` file to laptop. I have no clue where is CLIport and Data port.

Best

Jet

**Comment by ibaiGorordo** [comment]
Hi Jet,
Are you trying to analyze pre-recorded adc data? If that is the case, this repository is not useful for that. 

This repository is more like a simplified Python version of the data visualizer that helps to visualize/record the point cloud data, but not the raw data (because I do not have a device to read the raw data).

If you search in github, I think there are some python repositories for analyzing the raw adc data.

**Comment by yujianyuanhaha** [comment]
@ibaiGorordo  thanks,  the visualize/record the point cloud data are pretty good to go for me. I realize your work can fit into  mmWave demo visualizer at https://dev.ti.com/gallery/view/mmwave/mmWave_Demo_Visualizer/ver/2.1.0/.

Thanks again.


Jet

**Comment by yujianyuanhaha** [comment]
@ibaiGorordo  thanks again, I can now successfully get the x-y location data.


is there any way we can get some other plot which are in **mmWave_Demo_Visualizer** tool, such as 

- range profile
- doppler-range
- range-azimuth heatmap
- range-dopple heatmap

![image](https://user-images.githubusercontent.com/9403813/134045397-302bdaeb-4945-46ed-a340-49fcab051063.png)
I feel like current code has provide some information, make it close to those other plots.






Best

Jet
