### ISSUE TITLE
Do I need to install mmWave sdk to use this repository?

### ISSUE THREAD

**Issue by massolala** [ibaiGorordo/IWR1443-Read-Data-Python#16]
hello, it's good work, I have some question as follows.
1. What format the captured data is in, and whether it can be saved
2. I excute the .py program, then appear like this figure, nothing in figure. What went wrong maybe?
![image](https://user-images.githubusercontent.com/18341989/143454983-17e59027-e930-4927-8584-d6470d5761db.png)

**Comment by massolala** [comment]
![image](https://user-images.githubusercontent.com/18341989/143455119-2f9cefb3-c810-4667-8ef0-59ef14198470.png)

**Comment by ibaiGorordo** [comment]
Which device and SDK version are you using?

It is very likely that you don't have the SDK v1 in your device, which is the one in this repository.

For SDK 02_xx_xx_xx: https://github.com/ibaiGorordo/AWR1642-Read-Data-Python-MMWAVE-SDK-2
For SDK 03_xx_xx_xx: https://github.com/ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-

**Comment by massolala** [comment]
> 

My device is IWR1443 ES3.0, and SDK version is 3.05. 
When this sdk is used, I only used it when I flashed the machine.

**Comment by ibaiGorordo** [comment]
In that case don't use this repository, use this one instead:
https://github.com/ibaiGorordo/AWR1843-Read-Data-Python-MMWAVE-SDK-3-

Also, you might need to generate your own .config file since the .config file in that repository is for the Xwr1843. You can use the demo visualizer to play with different values and save the configuration that suits you.
https://dev.ti.com/gallery/view/mmwave/mmWave_Demo_Visualizer

Ibai
