### ISSUE TITLE
Using IWR1443 to measure velocity

### ISSUE THREAD

**Issue by ziqeskimo** [ibaiGorordo/IWR1443-Read-Data-Python#8]
Hi Ibai,

Newbie here. I understand from your code that your application is for up to 1 meters with a maximum radial velocity of 1m/s. I am currently using this board for my project to measure the velocity at about 10 meters with a maximum velocity of 15m/s. Could you guide me on how I could modify your code to meet the needs of my project?

As of now, below are the changes I have made so far:
1. Changed the serial ports 
2. Changed the number of Tx Antenna to 2
3. Added "print(dopplerVal)" to display the velocity captured

All help is appreciated. Thanks in advance! :)

**Comment by ibaiGorordo** [comment]
Hi,

I just want to make sure, what board and SDK version are you using?

So, basically what you want to do is change the configuration file (.cfg) so that the radar is configured the way you want. You can do that using the mmWave demo visualizer (https://dev.ti.com/gallery/view/mmwave/mmWave_Demo_Visualizer/ver/3.4.0/). There, you can configure your board with the velocity and range you want and you can also test how it works. Then, you just wave to save that configuration to your computer and add that configuration file to this repository.

You will have to change the Line 8 (configFileName = ) with the name of your configuration file.

If you increase the range, you will have to increase the plot limits (Line 309 and 310):
p.setXRange(-0.5,0.5)
p.setYRange(0,1.5)

Let me know if you have more questions
Ibai

**Comment by ziqeskimo** [comment]
Hi Ibai,

Thanks for your response. I am currently using the Texas Instruments IWR1443BOOST together with SDK 2.01.00.04
I will try it out and will update here again.

**Comment by ziqeskimo** [comment]
Hi Ibai,

Update: It works now. Thanks a lot!

**Comment by ibaiGorordo** [comment]
Hi,

I am glad to hear that. Also, you might have done it already, just to make sure if you are using the SDK 2, you should uncomment lines 188 and 189.

Ibai

**Comment by ziqeskimo** [comment]
Hi Ibai,

I tried to uncomment both lines, but the program will freeze. When i put it back as comments, it worked. Weird, but I don't know why too.

**Comment by ibaiGorordo** [comment]
I am not sure either, but I am glad it works well.

I will close the issue, if you have any other problem let me know.

Ibai
